### ISSUE TITLE
[rtx] mapping lemmas?

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-eng-kir#10]
I'm having trouble mapping lemmas in conditional output.  Is there a way to do this?

**Comment by jonorthwash** [comment]
I'm trying to turn noun lemmas into preposition lemmas.  @mr-martian, is this supported?

**Comment by mr-martian** [comment]
```
lemh > preposition : [same conversions]
2(lemh=2.lemh>preposition)
```
should work, though I'd want to test it to be sure.
