### ISSUE TITLE
[rtx] DP[VP[vP[v.*.ger]]] should be pprs or to@pr inf not finite

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-eng-kir#3]
`DP[VP[vP[v.*.ger]]]` should be `pprs` or `to@pr inf`(probably with ability to base it on the main verb), not a finite form.

As an example, "Балдар ойногонду жакшы көрөт." should be "Kids like playing" or "Kids like to play", and not "the Kids likes plays".

**Comment by jonorthwash** [comment]
@mr-martian, I'm having trouble getting the condition `(if (2.lem in ky_verbs_ing)` to evaluate as true when the lemma is "жакшы көр".  Example: "Күчүк балдар менен ойногонду жакшы көрөт."

**Comment by mr-martian** [comment]
```
ky_verbs_ing = башта бүтүр "жакшы көр" ;
```
I don't know why it doesn't work with the slash escape, but it does work with double quotes.

**Comment by jonorthwash** [comment]
Ah, I didn't realise both were available...

**Comment by mr-martian** [comment]
problem was it was including the slash in the string and matching against "жакшы\ көр". Both should work now.

**Comment by jonorthwash** [comment]
@mr-martian, now I'm having trouble making the `en_nonfin` attribute to propagate down the tree to the verb.  I'm looking for not just a solution, but in this case, I'm also curious how to go about debugging this using the `-e` mode.

**Comment by jonorthwash** [comment]
> Both should work now.

I prefer the quote method, so I'll stick with that, but it's good to know both will work!

**Comment by mr-martian** [comment]
I would probably try looking at the rule in question and then look at the rules right after it and see if the parent nodes there have the tags you expect.

**Comment by mr-martian** [comment]
as for getting it to the verb itself, maybe something like
`1(tense=(if (en_nonfin not = noNF) en_nonfin else tense))`

**Comment by jonorthwash** [comment]
The parent nodes don't have the tags I expect.  How do I debug this aspect of it?

(I'll try your suggestion for propagation a bit later—it looks like a better approach than what I was trying.)

**Comment by mr-martian** [comment]
You can try the same trick and see whether the previous rule sets those tags. You can also scroll back farther and find the input rule that built it. If neither of those work you can try `-s` and trace the bytecode, though that's likely to be not especially illuminating.

**Comment by jonorthwash** [comment]
I guess this is basically solved for now...
