### ISSUE TITLE
[rtx] regression: prepositions are no longer added

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-eng-kir#5]
Prepositions don't seem to be added anymore.  This is a regression.  Some sentences that did work that now do not work include the following:

* Мен Нарында туристти көрдүм. → (currently) I saw the tourist #Naryn. (should be "in Naryn")
* Мен муздаткычтан тамакты алдым. → (currently) I got the food the refrigerator.  (should be "from the refrigerator")

**Comment by jonorthwash** [comment]
@mr-martian, any thoughts on what might've happened with the `prep_flag` ?

**Comment by mr-martian** [comment]
The issue is that `PP -> DP` is unweighted so it doesn't have any basis on which to prefer `VP -> PP DP vP` over `VP -> DP DP vP`. Adding a weight to `PP -> DP` fixes this.
