### ISSUE TITLE
[rtx] regression: verb fronting is broken

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-eng-kir#6]
@mr-martian 

```
-Can't you eat the tasty meat?
-Aren't you eating the tasty meat?
-Weren't you eating the tasty meat?
-Didn't you want to eat the tasty meat?
-Don't you eat the tasty meat?

+Can't/Cannot you can eat the tasty meat?
+Are you are #eat the tasty meat?
+Weren't you were eating the tasty meat?
+Didn't you wanted to eat the tasty meat?
+Don't you do not eat the tasty meat?
```

**Comment by mr-martian** [comment]
`VP` and `vP` don't have `qst` in their patterns, so clipping always gives the empty string and the if statement in the macro fails.

**Comment by jonorthwash** [comment]
Ah, that makes sense, and fixing that helped a lot.  But there seems to be some tense and negation stuff that's still off (but only sometimes):

```
-Did you want to eat the tasty meat?
+Did you wanted to eat the tasty meat?

-Aren't you eating the tasty meat?
+Are you eating the tasty meat?

-Didn't you want to eat the tasty meat?
+Didn't you wanted to eat the tasty meat?
```

**Comment by jonorthwash** [comment]
\o/

**Comment by jonorthwash** [comment]
@mr-martian, Some of these still don't seem to be working.  Any thoughts?

```
$ echo "А Айгүлдүн күчүгү барбы?" | apertium -d . kir-eng
And do Aygül's puppy is present?
```

Should be "And is Aygül's puppy present?", or eventually (when #4 is solved), "And does Aygül have a puppy?"

**Comment by mr-martian** [comment]
There was a but preventing `%` from propagating lemmas, hence "do" rather than "be". There was also a bit of tweaking necessary to get the right form of "be".
