### ISSUE TITLE
[rtx] NP.*.gen NP.*.[px3] rule getting trimmed?

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-eng-kir#7]
Instead of combining `NP.*.gen NP.*.[px3]` into a single `DP`, it casts them into individual `DP`s which can then become `PP`s, arguments of verbs, etc.

`Мен тооктун этин жакшы көрөм.`
```
^unknown<S>{
	^Unknown<DP><nom><nom>{
		^Мен<prn><pers><p1><sg><nom>/Prpers<prn><CD><p1><mf><sg><nom>$
	}$
	^unknown<VP><fin><tv><aor><p1><sg><pos><QD>{
		^unknown<PP><of>{
			^unknown<DP><gen><of>{
				^тоок<NP><n><ND><PSD><gen><of>{
					^тоок<n><gen>/chicken<n><gen>$
				}$
			}$
		}$
		^unknown<DP><acc><NOpr>{
			^эт<NP><n><ND><px3sp><acc><NOpr>{
				^эт<n><px3sp><acc>/meat<n><px3sp><acc>$
			}$
		}$
		^жакшы көр<vP><tv><aor><fin><p1><sg><pos><QD>{
			^жакшы көр<v><tv><aor><p1><sg>/like<vblex><aor><p1><sg>$
		}$
	}$
}$
```

@mr-martian, any thoughts on how to avoid this?  I'm using `rtx-proc -F`.

**Comment by mr-martian** [comment]
Parse with `DP{NP NP}` has weight 6, parse above has weight 7, changing the rule in question from weight 2 to weight 4 fixes the issue.

**Comment by jonorthwash** [comment]
I'm thinking a debug mode that shows all the possible parses and the weights along with how they're computed might be useful..

**Comment by mr-martian** [comment]
I'll add notes about weights to `-e` on Monday.
