### ISSUE TITLE
[rtx] $nptype can't be dynamic?

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-eng-kir#9]
I'm having problems with this `DP` rule:
* `      NP cnjcoo %NP [$number=pl,$nptype=np] { 1 _1 2 _2 3 }`

Currently I'm forcing the value of `$nptype`.  When I set `$nptype=1.nptype` or let it try to set it automatically from `2` (by not specifying), I end up with `<NP><NP>` instead of `<NP><np>` or `<NP><n>` (depending on input).  `nptype` is defined as follows:
* `nptype = n np ;`

Here are some example sentences:
* Азамат менен Айгүл бакчада.
* Мышык жана күчүк бакчада.

@mr-martian, any idea why it's doing this?

**Comment by mr-martian** [comment]
The regular expressions were being compiled as case-insensitive. I have corrected this.
